# Generated by Django 4.2 on 2023-05-25 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the channel name', max_length=50, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL', max_length=255, unique=True, verbose_name='URL')),
                ('description', models.CharField(help_text='Enter the channel Description', max_length=255, verbose_name='description')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='channel creation date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to=settings.AUTH_USER_MODEL, verbose_name='channel author')),
                ('current_users', models.ManyToManyField(blank=True, help_text='Select the current channel users', related_name='current_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the search tags', max_length=30, verbose_name='search tags')),
                ('slug', models.SlugField(help_text='URL', max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels_app.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(help_text='Choose the search tags', related_name='channels', to='channels_app.tag', verbose_name='channel tags'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='channels_ap_created_bde68d_idx'),
        ),
    ]
