# Generated by Django 4.2 on 2023-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Enter the search tags', max_length=30, verbose_name='search tags'),
        ),
    ]
