# Generated by Django 4.2 on 2023-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['-date'], name='channels_ap_date_b37c9d_idx'),
        ),
    ]
