# Generated by Django 4.2 on 2023-04-17 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels_app', '0002_channel_current_users_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='current_users',
            field=models.ManyToManyField(blank=True, related_name='current_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
