# Generated by Django 4.2 on 2023-05-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
