# Generated by Django 4.2 on 2023-04-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0003_alter_channel_current_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='current_users',
        ),
    ]
