# Generated by Django 4.2 on 2023-04-20 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels_app', '0004_remove_channel_current_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='current_users',
            field=models.ManyToManyField(blank=True, related_name='current_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
