# Generated by Django 4.2 on 2023-04-21 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels_app', '0005_channel_current_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='tag',
        ),
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(help_text='Choose the search tags', related_name='channels', to='channels_app.tag', verbose_name='channel tags'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='current_users',
            field=models.ManyToManyField(blank=True, help_text='Select the current channel users', related_name='current_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
