# Generated by Django 4.2 on 2023-05-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='is_friend',
            field=models.BooleanField(default=False),
        ),
    ]
