# Generated by Django 4.2 on 2023-05-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_friend_is_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-id']},
        ),
    ]
