# Generated by Django 4.2 on 2023-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_friend_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, max_length=255, verbose_name='User description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='/static/channels_app/img/anonymous.png', upload_to='', verbose_name='User avatar'),
        ),
    ]
