# Generated by Django 4.2 on 2023-05-31 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_account_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, help_text='Range from 1 to 5', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='User rating'),
        ),
    ]
